
import maya.cmds as cmds

from dev.utils import convert_list_to_str

from rig.objects.object_data import MetaNode, DagNodeData
from rig.objects.base_object import BaseObject
from rig.joints.joints import Joints
from rig.controls.control import Control

class OsseousBase(BaseObject):

    def __init__(self) -> None: ...

    #... Pulbic Methods ...#
    def create(self) -> OsseousBase: ...
    
    #... Private Methods ...#
    def _create_module_structure(self) -> None: ...

    def _create_root_joint(self) -> None: ...

    def _create_root_control(self) -> None: ...
    
    #... Properties ...#
    @property
    def joints_grp(self) -> DagNodeData: ...
    
    @joints_grp.setter
    def joints_grp(self, value: DagNodeData) -> None: ...

    @property
    def joints_utils(self) -> DagNodeData: ...
    
    @joints_utils.setter
    def joints_utils(self, value: DagNodeData) -> None: ...

    @property
    def modules_grp(self) -> DagNodeData: ...
    
    @modules_grp.setter
    def modules_grp(self, value: DagNodeData) -> None: ...
    
    @property
    def controls_grp(self) -> DagNodeData: ...
    
    @controls_grp.setter
    def controls_grp(self, value: DagNodeData) -> None: ...

    @property
    def root_joint(self) -> DagNodeData: ...

    @root_joint.setter
    def root_joint(self, value: DagNodeData) -> None: ...

    @property
    def root_ctrl(self) -> DagNodeData: ...

    @root_ctrl.setter
    def root_ctrl(self, value: DagNodeData) -> None: ...


class Osseous(BaseObject):

    def __init__(self, name: str, side: str, desc: str, index: int, num_joints: int,
                 parent: Osseous, up_type: str): ...
    
    #... Public Methods ...#
    def create(self) -> Osseous: ...

    #... Private Methods ...#
    def _check_parent(self, parent: Osseous) -> None: ...
    
    def _create_module_structure(self) -> None: ...

    def _create_joints(self) -> None: ...

    def _parent_joints(self) -> None: ...

    def _space_joints(self) -> None: ...
    
    def _create_controls(self) -> None: ...
    
    def _create_aim_setup(self) -> None: ...
        
    def _create_annotations(self) -> None: ...

    #... Properties ...#
    @property
    def name(self) -> str: ...

    @property
    def side(self) -> str: ...

    @property
    def rig_module(self) -> DagNodeData: ...
    
    @rig_module.setter
    def rig_module(self, value: DagNodeData) -> None: ...

    @property
    def end_joint(self) -> DagNodeData: ...
    
    @end_joint.setter
    def end_joint(self, value: DagNodeData) -> None: ...
    
    

